# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewSumm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewSumm

pod 'Toast', '~> 3.1.0'

  target 'NewSummTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewSummUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
